### ISSUE TITLE
[bug?] debugger code not scrolling up if green arrow at the very top of the code window

### ISSUE THREAD

**Issue by maxiwamoto** [openMSX/debugger#111]
If you tracing code in the debugger and green arrow is currently pointing at the top line, if you press arrow up to scroll the code, the scrolling doesn't work. If you press (even once) scroll down button, you can scroll up without issues.

**Comment by pvmm** [comment]
Can you check if this still happens after pull request #107?

**Comment by maxiwamoto** [comment]
Latest build not going into mode where arrow at the top of the screen. It always in the middle, so scrolling working great all the time. And I personally like when code is not moving to the top line like it was in the version with the issue. 
Max

Sent from Yahoo Mail on Android 
 
  On Tue., 5 Apr. 2022 at 11:55, Pedro de ***@***.***> wrote:   


Can you check if this still happens after pull request #107?

**Comment by MBilderbeek** [comment]
@maxiwamoto To be fully clear: is this issue fixed now then? So can it be closed?

**Comment by maxiwamoto** [comment]
I believe the new version (#112) the code has been changed so after going into subroutine while tracing the code the cursor is not moved to top up position. This is the way debugger always been before it was changed some time ago. I believe this was the change that caused the issue. Since now its back as before, where you always trace code at the middle of the screen, the issue doesn't exist. And I personally like this way, because you can see code above where you trace. 

Sent from Yahoo Mail on Android 
 
  On Wed., 6 Apr. 2022 at 5:08, Manuel ***@***.***> wrote:   


@maxiwamoto To be fully clear: is this issue fixed now then? So can it be closed?

**Comment by MBilderbeek** [comment]
OK, then we can close this issue. Thanks for the follow up.

**Comment by maxiwamoto** [comment]
Will do

Sent from Yahoo Mail on Android 
 
  On Tue., 5 Apr. 2022 at 11:55, Pedro de ***@***.***> wrote:   


Can you check if this still happens after pull request #107?
