### ISSUE TITLE
Disappearing child windows on macOS

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/debugger#149]
The child windows opened by the debugger have an annoying behavior on macOS: all of them disappear when the application loses the focus.

This makes the activity of comparing their contents with another app an unnecessary gymnastic of refocusing and window hunting.

This behavior seem to be caused by the QT::Tool flag being applied to such windows. But such behavior is rarely done on native macOS apps, and in the very few cases I could find, those were not windows that hold content, but only things like tool pallets.

Since the debugger doesn't have such type of tool pallets, please disable the QT::Tool flag for all child windows since they hold content that must be seen when the App looses its focus.

Or, if there's anyone that actually like such behavior, at least add an option to enable/disable such behavior in the preferences.

**Comment by pvmm** [comment]
According to PR b6509f3, Qt::Tool flag is necessary because otherwise the floating window has no sizegrip (the bottom-right handle that lets you resize the window).

**Comment by pvmm** [comment]
b6509f35b94d7f7b8ec71dd0408ba7d032d3705e as inspiration.

**Comment by pvmm** [comment]
I guess #154 fixes this.

**Comment by sdsnatcher** [comment]
From what I tested, #154 satisfactorily fixes the problem. I'll try to close the issue.
