### ISSUE TITLE
[Bug] debugger ignoring symbols on SYM file [sf#441]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/debugger#16]
**Reported by sd-snatcher on 2012-09-17 02:48 UTC**
The debugger is ignoring symbols on some SYM files.

Steps to reproduce:

1) Load the attached sym file
2) Check for the EXPTBL symbol

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2012-09-17 02:48 UTC**
MSX variables SYM file
Attached file MSXvars.sym.zip:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/2bc279fc/2083/attachment/MSXvars.sym.zip

**Comment by openMSX-import** [comment]
**Commented by edwinv on 2012-09-22 10:49 UTC**
I did and it's there.

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2012-09-23 05:57 UTC**
1942 SYM files
Attached file 1942_SYM_files.zip:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/2bc279fc/33c4/attachment/1942_SYM_files.zip

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2012-09-23 05:58 UTC**
That's why I posted the feature request \#3569104. Sometimes it just refuses to load certain SYM files, sometimes it loads them well.

I attached another file that the debugger is refusing to load now. I even have two versions of the file: One is the original output by SjAsmPlus, the other one was adjusted by a script to try to be accepted by the debugger.

**Comment by openMSX-import** [comment]
**Commented by grauw on 2014-01-06 00:46 UTC**
Hey,

I have this bug report here for glass:

https://bitbucket.org/grauw/glass/issue/2/openmsx-does-not-recognize-symbols-in

I’m outputting symbol addresses with an uppercase H. Pasmo does as well. It looks like it’s processed as a “Sjasm file”. Could you make the parser case-insensitive for the H? Then you’d be processing the symbols of two more assemblers. E.g.

    QStringList a;
    a = l.at(1).split("h");
    if (a.size() != 2) {
        a = l.at(1).split("H");
        if (a.size() != 2)
            continue;
    }

**Comment by sdsnatcher** [comment]
It's still a nightmare to convince openMSX-debugger to read sym files. Could someone please explain why it just ignores the symbols contained in the attached file?


[MSXvars2.sym.zip](https://github.com/openMSX/debugger/files/1049628/MSXvars2.sym.zip)

**Comment by MBilderbeek** [comment]
I just tried it and it works fine... Where did you get your openMSX debugger binary from?

The last code updates were from November 2016.

In the code you can see which formats are supported: https://github.com/openMSX/debugger/blob/master/src/SymbolTable.cpp

**Comment by sdsnatcher** [comment]
Sorry, I attached the wrong file. I had done a lot of search/replace on this one to use 0x for the hexadecimal codes, as this seem to convince the debugger to load the files. Here's the file I had before all the reformatting:

[MSXvars.sym.zip](https://github.com/openMSX/debugger/files/1053442/MSXvars.sym.zip)

**Comment by MBilderbeek** [comment]
This one also seems to work here, but please try the very latest Debugger. I did a small update so that it ignores lines that do not contain useful data. That may have fixed it, although I haven't done any effort to check that.

**Comment by sdsnatcher** [comment]
The newest I have access is the one in this link. Is it the very latest?

http://openmsx.fixato.net/builds/mac/debugger/

**Comment by MBilderbeek** [comment]
Niek is trying to get the latest uploaded. I hope it appears soonish!

**Comment by MBilderbeek** [comment]
It seems it got there. Please try it and tell me about your findings.

**Comment by sdsnatcher** [comment]
Works like a charm now.  It also solved another bug: I was having a high rate of disconnections when I used the "View Bitmapped VRAM" feature.

**Comment by MBilderbeek** [comment]
Great! Thanks for reporting back. I guess I can close the ticket now.
