### ISSUE TITLE
"Go to address" won't work when a label is provided

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/debugger#169]
System:

- OS: Windows 10 Pro
- Emulator: OpenMSX 18.0

Steps to reproduce:

- Start a program on the virtual MSX
- Break the execution
- Load the .SYM file containing names
- Press CTRL+G (Go to address)
- Enter the name of a label and click Ok.

Result: the code view won't show the address of the entered label. However, it does work if the same label is entered in the "address" field on the "Main memory" view.

**Comment by MBilderbeek** [comment]
Hi, thanks for reporting. Can you also please specify which version of the debugger you are using exactly?
@pvmm can you comment?

**Comment by Colpocorto** [comment]
> 

I just downloaded the latest release available on this repository (nightly from 2022-04-06). I've checked version at the "About" menu and it's "0.10.0-unknown" but I guess this form hasn't been updated in decades.

**Comment by MBilderbeek** [comment]
Aren't there newer ones here: https://github.com/openMSX/debugger/releases/tag/nightly ? Please try these first.

**Comment by Colpocorto** [comment]
Thank you for your response. I've tried the latest one from the link you provided. Same result.

**Comment by MBilderbeek** [comment]
You're right, I can confirm it's not working. The label is shown, but jumping to it doesn't work. Jumping to an address works fine. According to the code, it should look up the address from the label, so it is supposed to work.
@pvmm would you like to take a look what's going wrong?

**Comment by pvmm** [comment]
#171 fixes this

**Comment by pvmm** [comment]
Can we close this?

**Comment by m9710797** [comment]
@Colpocorto Can you confirm the latest version (from today) fixes the problem for you?

**Comment by MBilderbeek** [comment]
Not sure how these files from Jan 27 have been built... I guess these are the left-overs that are mentioned in #172 ? Anyways, the ming32 one is indeed 64-bit, use that one please.

**Comment by Colpocorto** [comment]
> @Colpocorto Can you confirm the latest version (from today) fixes the problem for you?

I confirm the fix works perfectly.
Thank you very much.
