### ISSUE TITLE
[Bug] Errors on the VDP register view window [sf#442]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/debugger#17]
**Reported by sd-snatcher on 2012-09-25 00:56 UTC**
There are some errors on the " VDP register view" window:

\- Under the "Decoding V9958 registers" box, the CPU waitstate status is inverted.
- The "access address" shown is incorrect
- Not all register groups are resizable: "Table Base Address Registers" resize ok, but the other register groups don't. "Display registers" even move over the "Color Registers" group when the window is resized.
- On Mac OS-X, the texts for each bit of the registers (8 little boxes) are usually cropped. (see attached screenshot)

Extra: Not an error, but this window is huge on the V9958 mode! Please try to reduce it a little.

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2012-09-25 00:56 UTC**
VDP register window - Mac OS-X screenshot
Attached file Screen%20shot%202012-09-24%20at%2021.54.33.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/d2a1e750/5dfa/attachment/Screen%20shot%202012-09-24%20at%2021.54.33.png

**Comment by MBilderbeek** [comment]
I think most important issues mentioned in this ticket are now solved:
- 3334648599656fcd8b66b45c28edf434aca260a0 Fix inverted description of WTE
- 89f17f88e6b978e0d6140561f7e7655a7501bd55 Updates button sizes for better readability.
If there are remaining issues, please create separate tickets for them. (And use the latest code to test.)
