### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by wijnen** [openMSX/debugger#50]
While building the debugger for Debian (which adds some extra build flags), there are some warnings about possibly uninitialized variables.  I haven't looked into them.

For those that are false positives, they can be silenced by initializing the variable to any value.  For true positives, they are bugs that should be fixed. :-)

A complete list:

  src/DisasmViewer.cpp:228:14: warning: ‘a’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  /usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h:170:60: warning: ‘h’ may be used uninitialized in this function [-Wmaybe-uninitialized]`
  src/DockableWidgetLayout.cpp:115:33: warning: ‘dist’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  src/SymbolManager.cpp:374:54: warning: ‘regMask’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  src/SymbolManager.cpp:373:52: warning: ‘slotMask’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  src/SymbolManager.cpp:425:40: warning: ‘type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  src/SymbolTable.cpp:646:47: warning: ‘sym’ may be used uninitialized in this function [-Wmaybe-uninitialized]

**Comment by MBilderbeek** [comment]
I think all these warnings have been fixed now.
