### ISSUE TITLE
White window

### ISSUE THREAD

**Issue by djcaetano** [openMSX/debugger#54]
When opening the debugger, it is correctly drawn; once I try to resize the window and/or open a menu or something, the result is a white window:
![test](https://cloud.githubusercontent.com/assets/19708827/20406429/6d66b4d4-acf4-11e6-977e-dcbe72b04099.jpg)
I am running openMSX 0.13.0 and the latest debugger (both 32 bit) on a Windows 10 machine (64 bit). I have already tried openMSX 0.13.0 64 bit. The result is the same. In fact, the problem persists even if only the debugger is running.

**Comment by MBilderbeek** [comment]
Thanks for reporting!

The version of openMSX is not related, the debugger is a separate program and runs on its own. That explains why running openMSX isn't influencing the problem.

Anyway, I don't know how to solve this. All I can say it works fine on Linux here... and I haven't heard about any complaints from other people on Windows either. So, I'm not sure what is going on here...

We are still trying to get the latest debugger compiled (with Qt5) with Visual Studio. Once that is successful, I suggest you try that build.

**Comment by MBilderbeek** [comment]
@djcaetano Do you still have this issue with the latest debugger build?

**Comment by MBilderbeek** [comment]
Assuming it's solved, closing... (No response from @djcaetano .)
