### ISSUE TITLE
Breakpoint list needed in debugger GUI

### ISSUE THREAD

**Issue by Wierzbowsky** [openMSX/debugger#61]
This is a feature request. While working with breakpoints in the debugger it is sometimes necessary to enable or disable certain breakpoints. While breakpoints set by F5 are clearly visible by red dots in the GUI, other breakpoints are not visible anywhere. Moreover, there's no way to see all of them in one window. So I propose to add "Breakpoint list" dialog into the Breakpoints menu. This dialog should display the following info:

- breakpoint type
- enabled/disabled status
- breakpoint address and properties (slots, range, etc.)

There should be a way to enable, disable or delete breakpoints from this list. Such modification will make debugging much easier when using various types of breakpoints.

**Comment by MBilderbeek** [comment]
Adding a list is not a big problem, but enabling/disabling is not that easy. The openMSX core doesn't have any functionality to do that at the moment.

**Comment by Wierzbowsky** [comment]
Well, maybe editing the parameters of the breakpoint would be possible. This way it may be invalidated. For example some of those breakpoints may be hit by BIOS very often and that ruins the debugging session. If the breakpoint's parameters can be altered live, then such problem could be mitigated.

**Comment by MBilderbeek** [comment]
If we merge this with #46 : also enable editing of break points :)

**Comment by pvmm** [comment]
I am working on this feature. See #91
