### ISSUE TITLE
Debugger takes too long to connect to the emulator, finds multiple sessions

### ISSUE THREAD

**Issue by Wierzbowsky** [openMSX/debugger#62]
With the latest at the moment version of OpenMSX the latest available debugger version has a few issues. First, it takes up to 1 minute to connect to the running OpenMSX session. Second, even if one OpenMSX session is running, the debugger outputs a dialog asking to select the session to connect to. There may be 2 or 3 sessions in that list while only one physical session exists in OpenMSX.

I will attach the screenshots later.

**Comment by MBilderbeek** [comment]
Did you try what wilsonpilon said here: https://www.msx.org/forum/msx-talk/general-discussion/help-openmsx-debugger ?

> Hi, you check for any zombie openmsx process or orphaned socket file?
Try to clear any file in %USER%/AppData/Local/Temp/openmsx-default and %USER%/AppData/Local/Temp/openmsx before start the openmsx and debugger.

If there are many stale/orphaned socket files the connection can take a long time.

**Comment by Wierzbowsky** [comment]
Cleaning the "openmsx-default" folder helped, thanks! Now there's no delay and the debugger doesn't complain about multiple open sessions. Btw, I noticed that those folders are deleted by OpenMSX on exit. But in my case it didn't happen for quite a long time. As a result the files were piling up there for many weeks.

I would suggest that OpenMSX cleans up those folders when it starts and there are no other OpenMSX processes in memory. This way the problem may be mitigated.

**Comment by MBilderbeek** [comment]
I wonder why they weren't cleaned on exit in your cases. Perhaps openMSX crashed several times before it could clean?

**Comment by Wierzbowsky** [comment]
Quite possible.

**Comment by MBilderbeek** [comment]
Wouter suggested a different implementation: let the debugger delete the stale socket files when it concludes it is invalid.

**Comment by Wierzbowsky** [comment]
Fine with me as long as it doesn't take significant time.

**Comment by MBilderbeek** [comment]
I think this issue has been solved with newer versions of the debugger. Please reopen if I'm wrong, after checking on the latest build.
