### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by samsaga2** [openMSX/debugger#66]
How to build this on Windows?

I can see a sln file that seems to call a python (python2 file?). But anyway the project file has a lot of missing files (moc folder for example). I have no problem to compile this on linux but on windows I have no idea.

Maybe it's broken and I have to create a new qt project file and using qmake?

**Comment by MBilderbeek** [comment]
You need Python and Qt 5.7.0 installed.

**Comment by Vampier** [comment]
I'm going to make a few assumption here: 
1) you're using Visual Studio 2017
2) you've downloaded and unpacked the QT 5.7.0 source code and put this into the ../derived/3rdparty/src/qt5.7.0 folder
3) you are running a 64bit windows variant (7/8/10/etc)

Currently you can only compile the 64bit version. You open the SLN and compile it. I compile directly from the command line using msbuild. 

Let me know if this works for you.

**Comment by MBilderbeek** [comment]
I don't think there's really an issue. Closing.
