### ISSUE TITLE
Glitch that happens on real Turbo-R doesn't happen on openMSX

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/debugger#68]
When running the game Laydock-2 with the R800 CPU enabled, a lot of glitches occur during the game animated intro.

I suspect this is caused by a slowdown that the S1990 imposes on the R800 when the VDP palette port is accessed, then the intro color splitscreen goes nuts. This slowdown doesn't seem to occur at the same degree on openMSX, so it runs the intro without glitches.

Tested on the latest Mac build: openmsx-0.14.0-367-ge00e2d430-mac-x86_64-bin.dmg

Steps to reproduce:

1) Apply the attached IPS patch to the Laydock-1 disk1 image
2) Boot the game on openMSX and on a real FS-A1ST and compare the results

[Laydock2_R800.ips.zip](https://github.com/openMSX/debugger/files/2453531/Laydock2_R800.ips.zip)

**Comment by edwin-v** [comment]
Closing because this is not related to the debugger. I assume you submitted this to the actual openmsx repo by now.
