### ISSUE TITLE
Disassembly window improvement

### ISSUE THREAD

**Issue by NYYR1KK1** [openMSX/debugger#70]
I hope you could add a feature that if user double clicks a line where there is ie. "jr c,#d09a"-command the focus would automatically change to line where there is disassembly of address #d09a

You would also need to keep some short history of previous addresses & scrollbar positions in order to add "back"-button that would change the view back to situation before double click.

Effectively this would make following ie. code with "call"-commands more like looking in to folders in file explorer. (...and would make life SO much easier!)

If you want practical example of the idea, look ie. disassembly mode of Super-X and see how the right & left keys work in there.

**Comment by samsaga2** [comment]
You can press enter or right to jump to the address and left or backspace to return to the previous address.

**Comment by NYYR1KK1** [comment]
Yes, I think that would be quite ideal solution and not even hard to implement.

**Comment by samsaga2** [comment]
It's not hard because it's already implemented.. by me XD.

**Comment by NYYR1KK1** [comment]
Really? Then why it does not work for me? I've downloaded latest development build from https://openmsx.fixato.net/ (64bit Win10) and pressing mentioned keys in source view does not do anything for me.

**Comment by samsaga2** [comment]
You will need to compile the debugger yourself. The latest development build it is outdated.

**Comment by NYYR1KK1** [comment]
I see... These advanced computer languages & compilers are way over my head, but I just started poking Vampier a bit. I think that may help sooner or later. :)

Anyway, thank you a LOT for your contribution! This will make the debugger much more valuable for me.

**Comment by Vampier** [comment]
fear no more -  http://openmsx.vampier.net/openMSX_Debugger_x64_20191105.zip

have fun :)

**Comment by NYYR1KK1** [comment]
Thank you Vampier! It seems that you forgot "qwindows.dll" from this package, but not a problem.

@samsaga2 Thank you, this works great! I would not mind if this same functionality would work for commands like ld a,(#xxxx) or ld hl,#xxxx as well (to have a quick peek of the memory content), but even like this it already improves the usability a lot.

**Comment by MBilderbeek** [comment]
I guess this issue can be closed, as it was already implemented. For other new ideas or suggestions or of course bug reports, please open a new issue.
