### ISSUE TITLE
XML not (un)escaped on emulator side

### ISSUE THREAD

**Issue by pvmm** [openMSX/debugger#93]
I get this error
![image](https://user-images.githubusercontent.com/7815819/157768126-737a9b5b-c697-497b-a4b3-db49a0ce969c.png)

when I send breakpoints through XML documents to the emulator, since it doesn't convert them back. I created breakpoints `bp#5` and `bp#12` using **Add...** menu option on the debugger:
![image](https://user-images.githubusercontent.com/7815819/157772811-49c508c1-c68a-4b4d-84b4-1f50dbb4ce43.png)
`bp#9` is me experimenting with breakpoints created on the emulator side and it was **not** escaped when sent to the debugger. Should we unescape everything from the debugger side?

**Comment by m9710797** [comment]
Hi,
Can you provide more details? E.g. can you point me to the location in the debugger where this command is send?
I didn't look at the code yet (I'm at work right now, I could look at it this evening or tomorrow). But this is how I _expect_ the code should work:
* All code in the debugger should send commands un-escaped. And they can expect that this command string arrives in exactly this way at the openMSX side.
* Similarly for the return-path. The string returned from openMSX will arrive unaltered back in the debugger code.
* To make this possible there is exactly one location in the debugger code that add escaping on the send-path and removes it on the receive path. (I assume this code is located somewhere in "OpenMSXConnection", but I didn't check.)

**Comment by pvmm** [comment]
It's in DebuggerData.cpp. It escapes/unescape only the condition of breakpoints in `createSetCommand()`
```
        return cmd.arg(BreakpointSetCodes[type])
                  .arg(addr)
                  .arg(escapeXML(cond));
```
and `createRemoveCommand()`:
```
                newBp.condition = bp.mid(p, q - p).simplified();
                unescapeXML(newBp.condition);
                insertBreakpoint(newBp);
```
I can send a PR to remove them.

**Comment by pvmm** [comment]
OK. The problem is that escapeXML and unescapeXML change strings in place. They just return them for convenience, but I was using them to debug stuff. Not really an issue.

**Comment by m9710797** [comment]
Aha.
Feel free to change that, because it's indeed a confusing API.

**Comment by pvmm** [comment]
It's PR #96
